### ISSUE TITLE
.env files have dangerous code in them

### ISSUE THREAD

**Issue by perry-ca** [ZOSOpenTools/meta#105]
All of the .env files have a find command that looks for files containing a string starting from the current working dir.  This is dangerous.  If the user is in their home dir and runs `. zopen/prod/curl/.env` instead of `cd zopen/prod/curl; . .env` then they will end up doing a search and replace on their whole home dir.

**Comment by IgorTodorovskiIBM** [comment]
We have some code in the .envs to sort of guard for this situation:
```
if ! [ -f ./.env ]; then
  echo "Need to source from the .env directory" >&2
  return 0
fi
```
I think this will be easier to do if/when we start depending on bash

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM @perry-ca is this fixed?

**Comment by IgorTodorovskiIBM** [comment]
The guard (https://github.com/ZOSOpenTools/meta/issues/105#issuecomment-1374033790) is in place in all .env files. I'll let @perry-ca decide if we should close this or not.

**Comment by perry-ca** [comment]
The guard Igor mention should solve the problem.  I am curious what errors @v1gnesh got.

**Comment by v1gnesh** [comment]
@perry-ca Not errors but in general, shellcheck finds a load of things.
Example: I pasted the content of [zopen-build](https://github.com/ZOSOpenTools/meta/blob/main/bin/lib/zopen-build) here - https://www.shellcheck.net/
