### ISSUE TITLE
Introduce a basic test suite to validate the zopen tools


### ISSUE THREAD

**Issue by ZOSOpenTools** [ZOSOpenTools/meta#115]
These download / build tools are getting complex enough that I'm thinking we should have at least a basic test suite in place to validate the operation of the tools.
Can we open an issue for this - maybe leverage the zotsampleport and enhance it a bit for these purposes?

_Originally posted by @MikeFultonDev in https://github.com/ZOSOpenTools/utils/pull/97#pullrequestreview-1167176177_

**Comment by MikeFultonDev** [comment]
This is even more important now.

**Comment by IgorTodorovskiIBM** [comment]
I think we're in agreement that the testing should be done via [metaport](https://github.com/ZOSOpenTools/metaport). 
We may want to create a tests directory in meta though, which metaport can simply call.

We should probably have basic tests for all of the commands:
```
  init            generate $rootfs/etc/zopen-config, creates file structure and bootstraps
  build           invokes the build script.
  download        downloads z/OS Open Tools package(s)
  install         installs z/OS Open Tools package(s))
  generate        generate a zopen project
  update-cacert   update the cacert.pem file
  upgrade         upgrades already installed tools
  list            lists information about z/OS Open Tools packages
  query           queries z/OS Open Tools packages
  search          searches remote repo for z/OS Open Tools package
  remove          removes installed z/OS Open Tools packages
  alt             switch local versions of z/OS Open Tools packages
  clean           cleans various aspects of z/OS Open Tools packages
```
+ promote command

**Comment by MikeFultonDev** [comment]
Agreed! Please add in 'promote' too - and lower priority should be a basic test of the 'plumbing' commands too

**Comment by IgorTodorovskiIBM** [comment]
@MikeFultonDev , can we close this now that metaport has a basic test suite?
