### ISSUE TITLE
remove "command -V" check from resolveCommands()?


### ISSUE THREAD

**Issue by ZOSOpenTools** [ZOSOpenTools/meta#117]
I would like to make a change to the resolveCommands() function in zopen-build and I'm seeking some feedback.  Currently this function checks for the existence of the command (like command -V ./configure) before it sets the appropriate envar.  Unfortunately at this point sometimes the commands don't exist yet!  For example in the expat build configure is created only after the bootstrap phase.  This currently causes the configure step to be skipped because zopen thinks the configure command doesn't exist. I would like to remove the command -V check altogether.  Thoughts?

**Comment by MikeFultonDev** [comment]
Can whoever opened this identify themselves? Looks like it was opened by ZOSOpenTools. @IgorTodorovskiIBM ?
