### ISSUE TITLE
package manager tool?


### ISSUE THREAD

**Issue by ZOSOpenTools** [ZOSOpenTools/meta#120]
So far the `zopen` tool has been great for developers to work on porting OSS tools.  We will soon need a command/tool for installing and managing (upgrading?) these OSS tools and their version numbers, similar to other platforms' package management tools.  Any ideas here?

One idea is to have commands that allows for searching, listing local installations, and installing packages.  Example:
```
zopen list # List the locally installed packages
zopen search git # Search the list of available packages
zopen install git # Install the specified package
zopen purge git # Uninstall the specified package
```

Ideally, `zopen` would be both open sourced but also shipped with z/OS Unix so user's don't have to first install zopen on a fresh system, if that is possible.

**Comment by v1gnesh** [comment]
Would this work? - https://github.com/basherpm/basher

**Comment by MikeFultonDev** [comment]
Maybe. Have you tried it on another system?

**Comment by v1gnesh** [comment]
Nope, but it seems straightforward enough to evaluate for those who are comfortable with the current zopen workflows.

**Comment by MikeFultonDev** [comment]
not sure who opened this - it's against ZOSOpenTools. @IgorTodorovskiIBM ?

**Comment by IgorTodorovskiIBM** [comment]
Ah, these were migrated from utils, this was the original issue: https://github.com/ZOSOpenTools/utils/issues/49. @jshimoda9323
