### ISSUE TITLE
Warn instead of error out for missing .env file of PORT_GIT_DEPS programs?


### ISSUE THREAD

**Issue by ZOSOpenTools** [ZOSOpenTools/meta#121]
For the programs specified for `PORT_GIT_DEPS`, e.g make, git, they are already pre-installed somewhere on the machine I'm using, but I have to manually create empty `.env` files under `${HOME}/zot/prod/${dep}/.env` in order for the build.sh script to keep going and not report error during `checkDeps()` step. This gives a bit inconvenience and confusion.

**Comment by MikeFultonDev** [comment]
Is this still an issue? I would recommend people use the z/OS Open Tools make, git, curl, etc. and if they are using alternates, then it is probably useful to create the .env to 'fit into' the zopen model so the tools know how to set up the environment for the tool.

**Comment by MikeFultonDev** [comment]
I'm inclined to mark this 'not fix' unless there are more compelling details?
