### ISSUE TITLE
Extend build.sh to normalize test output for test comparison, regression identification


### ISSUE THREAD

**Issue by ZOSOpenTools** [ZOSOpenTools/meta#122]
Idea:
* Normalize the test output of various tools so that we can do actual/expected comparisons of each tests
* Jenkins can use a generic logic to identify regressions, report test failures

Implementation idea:
* build.sh will offload the parsing to a tool specific script like `portparsetests.sh` which will parse it into 3 fields (testcase, pass/fail, fail message) and store it into a csv or other standard file format (junit, tap)
* build.sh will perform a comparison of the expected test results (manually created by the author)

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM has done  a first iteration of this with the requirement for each port to scan tests and provide results
