### ISSUE TITLE
zopen-importenvs error

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/meta#146]
![image](https://user-images.githubusercontent.com/42328411/215491988-6a2ecbb9-372a-4f56-b084-e6f4a4065d80.png)

**Comment by IgorTodorovskiIBM** [comment]
@HarithaIBM can you take a look when you get a chance

**Comment by MikeFultonDev** [comment]
@lbdyck assuming this is fixed. Re-open if not.
