### ISSUE TITLE
bpxwunix 'line too long' error

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/meta#161]
This appears to be the issue I'm getting:

_CEE_RUNOPTS= FILETAG(AUTOCVT,AUTOTAG) POSIX(ON) FILETAG(AUTOCVT,AUTOTAG) POSIX(ON) FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)  . . . (repeats)

Notice anything off here :)

**Comment by lbdyck** [comment]
The same error continues with these environment  variable ( all are truncated due to the display)

PATH=/u/lbdyck/work/boot/meta-main.20230124_190355.zos/bin:/u/lbdyck/work/boot/curl-7.83.1.20230120_231325.zos/bin:/u/lbdyck 
-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  30 Line(s) not Displayed  
LIBPATH=/u/lbdyck/work/boot/curl-7.83.1.20230120_231325.zos/lib:/u/lbdyck/work/boot/perl5-blead.20221109_001219.zos/lib/perl 
-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  29 Line(s) not Displayed  
MANPATH=/u/lbdyck/work/boot/curl-7.83.1.20230120_231325.zos/share/man:/u/lbdyck/work/boot/bash-5.2.20230117_225051.zos/share 

Lengths are:
Path - 614
Libpath - 500
Manpath - 344
_CEE_RUNOPTS - 258

**Comment by lbdyck** [comment]
The issue is with running all the .env files which have these statements:

export _CEE_RUNOPTS="$_CEE_RUNOPTS FILETAG(AUTOCVT,AUTOTAG) POSIX(ON)"   
export PATH="${CURL_HOME}/bin:$PATH"                  
export LIBPATH="${CURL_HOME}/lib:$LIBPATH"            
export MANPATH="${CURL_HOME}/share/man:$MANPATH"      

There needs to be some more 'intelligence' with these to eliminate duplicates.

**Comment by lbdyck** [comment]
Note that I have a modified .bootenv or this would be worse

![image](https://user-images.githubusercontent.com/42328411/216988968-0d8a582a-ecc9-4f84-aa17-f80d467a3140.png)

**Comment by IgorTodorovskiIBM** [comment]
Thanks @lbdyck ! I think we need to rebuild the boot packages again, we recently added some code to remove dupes here: https://github.com/ZOSOpenTools/meta/blob/main/bin/lib/zopen-build#L1141

But we need to rebuild the packages and "boot" ports to reflect the change.

**Comment by lbdyck** [comment]
let me know after you've updated and i'll try afresh

**Comment by IgorTodorovskiIBM** [comment]
Each port's .env should add to and remove duplicates. I think .bootenv just sources each port's .env.

**Comment by lbdyck** [comment]
The bootenv does this:

```
cd "${p}"     
  . ./.env  
```  
  
 While (sample) .env does:
`export PATH="${CURL_HOME}/bin:$PATH" `

Thus the PATH (in this case) is added to and not checked for duplicates.

**Comment by IgorTodorovskiIBM** [comment]
After we rebuild all of the ports and create the boot releases, it should check for duplicates, unless zopen-setup is creating it's own .env, which I don't think is the case. CC @MikeFultonDev

**Comment by lbdyck** [comment]
This is what I see (sample)

For bootenv
![image](https://user-images.githubusercontent.com/42328411/217048534-c41b499f-73cc-4346-a000-72fc48e2279e.png)

and for .env
![image](https://user-images.githubusercontent.com/42328411/217048428-ef4fb22a-197e-436e-9698-dd45be2fb86b.png)

**Comment by lbdyck** [comment]
I don't know where these come from but at this point I do NOT want the coreutils included, and others, as I only want git and what it needs (coreutils has a version of cp that does not work the way the omvs provided cp works - i've opened a ticket on that).

**Comment by lbdyck** [comment]
I just reran zopen install and have an environment with these length:

PATH 758      
LIBPATH 758   
MANPATH 758   

A suggestion - only put the symlink instead of the full directory name into the .env

**Comment by MikeFultonDev** [comment]
I see this as part of our bigger issue of putting things in various locations and the need for a 'centralized' location. Would appreciate your thoughts - it's in this discussion @lbdyck : https://github.com/ZOSOpenTools/meta/discussions/110

**Comment by lbdyck** [comment]
Consider this issue fixed with the removal of the duplicates in  

`_CEE_RUNOPTS= FILETAG(AUTOCVT,AUTOTAG) POSIX(ON) POSIX(ON) `

My testcase proves that PATH/LIBPATH/MANPATH can be longer but this one variable was the issue.

1. run the /boot/.bootenv
2. env > envs.list
3. run this simple rexx:

`
/* rexx */                                                    
x = syscalls('ON')                                            
address syscall                                               
boot_path = '/u/lbdyck/zot/envs.list'                         
'readfile (boot_path) env.'                                   
say 'Environment variables:' env.0                            
l = 0                                                         
do t = 1 to env.0                                             
  if length(strip(env.t)) > l then l = length(strip(env.t))   
end                                                           
say 'Longest env:' l                                          
cmd = 'ls -la'                                                
x = bpxwunix(cmd,,so.,se.)                                    
say 'No Env - StdOut:  ' so.0 'StdErr:' se.0                  
x = bpxwunix(cmd,,so.,se.,env.)                               
say 'With Env - StdOut:' so.0 'StdErr:' se.0                  
x = syscalls('OFF') `

**Comment by MikeFultonDev** [comment]
Wonderful. Thanks for validating. Great work @IgorTodorovskiIBM
