### ISSUE TITLE
make `zopen install`'ed packages relocatable or preserve `download`?

### ISSUE THREAD

**Issue by covener** [ZOSOpenTools/meta#162]
Relative to this announcement about `zopen download` deprecation:

> Hi, please be aware that zopen download has been deprecated and will be replaced with zopen install. The key difference between these two options is that zopen install not only downloads and extracts the tool, but also sets it up for use, whereas zopen download only performed the first two actions.

I think one thing to consider for preserving `zopen download` is that for many packages it will bake in paths during the installation (sourcing of env.sh) This means the package directory cannot be moved.   The alternative would be grabbing the packages from their individual releases, but as time goes on you might be foregoing more and more package management features.

Beyond preserving download, another option is to make it so that the sourced env scripts can be re-run without looking for their original jenkins prefix.

> Good point! would you be able to open an issue? We might be able to handle it in a different way, as in we could make setup.sh smarter, it could probably store the initial install path somewhere and then on rerun of setup.sh update hardcoded references of that install path to the new one (if you they don't match).

**Comment by MikeFultonDev** [comment]
I think much of this has been fixed. @covener please re-open with details if you see remaining issues.
