### ISSUE TITLE
zopen upgrade leaves behind old versions.

### ISSUE THREAD

**Issue by ccw-1** [ZOSOpenTools/meta#174]
Please implement autoclean option in a similar manner as `apt autoclean`

**Comment by MikeFultonDev** [comment]
I think this is a 'feature'? @IgorTodorovskiIBM @DevonianTeuchter does our `zopen clean` let people clean up old releases now?

**Comment by IgorTodorovskiIBM** [comment]
`zopen clean -u` should remove unused packages or you can selectively remove packages using `zopen remove`

**Comment by MikeFultonDev** [comment]
working as designed. use zopen clean -u for cleanup
