### ISSUE TITLE
Sourcing diffutils/.env gives a non-zero return code

### ISSUE THREAD

**Issue by stevchen-ibm** [ZOSOpenTools/meta#175]
Sourcing the ./.env file under the installation directory of `diffutils` currently gives a non-zero return code.

The last line of the file contains the command `unset ZOPEN_SOURCING_DEPS`.

The following is the output I received:
```sh
+ [ ! -f .installed ] 
+ [ -f .depsenv ] 
+ unset ZOPEN_SOURCING_DEPS 
> echo $?
+ echo 1 
1
```

**Comment by IgorTodorovskiIBM** [comment]
Interestingly, unset returns 1 under /bin/sh vs 0 under bash

**Comment by IgorTodorovskiIBM** [comment]
Covered in PR https://github.com/ZOSOpenTools/meta/pulls

**Comment by IgorTodorovskiIBM** [comment]
Done in the latest zopen-install
