### ISSUE TITLE
Changing the way export statements are done.

### ISSUE THREAD

**Issue by ccw-1** [ZOSOpenTools/meta#184]
Currently the way to set environment variables is 

cd ..../install_dir/tool_name &&  .   ./.env; cd -

It produces a side-effect because changing current directory on the running shell can cause a lot of problems.

Since all .env does is to export ENVVAR.
I suggest this be done in a binary program that prints out 
```
export XXX=....
export YYY=....
export ZZZ=...
```
and the user set it by  

```
eval `installpath/toolname/env`
```

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM can you investigate as part of the re-work of env var set up?

**Comment by ccw-1** [comment]
I forgot exactly what. but it was something in the source'd script that failed because of cd.

**Comment by ccw-1** [comment]
Since the purpose of changing the directory is to find out the relative paths to set the envs. A program can do the same without changing directories.

**Comment by MikeFultonDev** [comment]
with all the rework and our short term intention to eliminate .env altogether, closing this off
