### ISSUE TITLE
Reasonable 'starter' compiler and linker options for projects

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/meta#2]
Define what good starter options to add to for a given project. 
The xlclang compiler is a good 'free' compiler everyone can use on z/OS:
- `CC=xlclang`

We want to look and smell as much like GCC as possible, and xlclang provides this out of the box:

We need to provide the number of signals to a few different tools. This can perhaps get removed in the near future since it doesn't seem like it should be necessary:
- `-DNSIG=39`

Since this is code we are porting, using the [latest features](https://tech.mikefulton.ca/ZOSFeatureTestMacros) available is in general good:
- `-D_XOPEN_SOURCE=600 -D_ALL_SOURCE` 

The code will expect to be ASCII, and we should build the tools as such:
- `-qascii  -D_AE_BIMODAL=1 -D_ENHANCED_ASCII_EXT=0xFFFFFFFF`

The code will expect to be IEEE floating point, not hex floating point. This is the default for xlclang, so no option is required.

**Comment by MikeFultonDev** [comment]
@perry-ca @ccw @IgorTodorovskiIBM would like your input on ^ since this is my 'trial and error' learning and may be off.

**Comment by perry-ca** [comment]
I'd leave the -std option out.  I think most projects set their own language level.  I think gnu11 is the default anyways. 

xlclang is always IEEE so no need for -qfloat=ieee.  

The -DNSIG=39 sounds like something specific to a package.  I don't think we should be suggesting people set that.

+1 to ascii & XOPEN_SOURCE.  We should also suggest people use a clang configuration of their package over an xlC configuration if one exists.

We shouldn't be doing the -qnose part.  The compiler has specific system directories and order that need to be followed.  For example, stdio,h for xlclang is not /usr/include/stdio.h.  The user should be able to just add -I<dir> and everything should work.  In special cases you can use -isystem <dir> to really treat the headers in <dir> as system header.  The only difference between `#include ""` and `#include <>` is the former looks at the directory the source file is stored in before looking at the include dirs.   The only real difference between -I and -isystem is any warnings coming from headers included via -isystem are suppressed.  They are handled differently by options like -qnostdinc but very few people use those.

**Comment by MikeFultonDev** [comment]
I updated based on your input @perry-ca . I kept the -DNSIG=39 but agree we should be looking to get rid of it. It is needed on a bunch of ports though - but perhaps once we are building everything from true git source (vs tarballs) then we can use autoconf to fix this properly.

**Comment by MikeFultonDev** [comment]
I've incorporated these options into build.sh (in utils repo). @perry-ca tell me if you are ok with me closing this issue
