### ISSUE TITLE
Create a common TOKEN reading mechanism across all tools on meta

### ISSUE THREAD

**Issue by HarithaIBM** [ZOSOpenTools/meta#220]
Create a common TOKEN reading mechanism across all tools on meta by using "ZOPEN_GITHUB_OAUTH_TOKEN" instead of GITHUB_OAUTH_TOKEN and ZOPEN_GIT_OAUTH_TOKEN

**Comment by IgorTodorovskiIBM** [comment]
Can we close this now @HarithaIBM ? I think this is done now

**Comment by HarithaIBM** [comment]
This is done, and build is successful. The information is announced on slack channels as well.
