### ISSUE TITLE
pax command to download code appears to require bash

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/meta#230]
See: https://github.com/ZOSOpenTools/meta/discussions/159

@IgorTodorovskiIBM and @lbdyck I closed off the 'discussion' since this is a bug and belongs here.

**Comment by IgorTodorovskiIBM** [comment]
Closing this as the release page one-liners have been updated to work on /bin/sh.

E.g. (no stdin redirection)
```
curl -o curl-7.88.1.20230313_115116.zos.pax.Z -L https://github.com/ZOSOpenTools/curlport/releases/download/curlport_749/curl-7.88.1.20230313_115116.zos.pax.Z && pax -rf curl-7.88.1.20230313_115116.zos.pax.Z && cd curl-7.88.1 && . ./.env
```
