### ISSUE TITLE
Considering adding zoslib implicitly to all projects

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/meta#235]
Currently, these are the only projects that do not have zoslib added as a dependency (17 in total):

- [x] ~./topport/buildenv~ - Does not build
- [x] ./patchport/buildenv - https://github.com/ZOSOpenTools/patchport/pull/1
- [x] ./help2manport/buildenv - No C files
- [x] ./zigiport/buildenv - N/A
- [x] ./cmakeport/buildenv - Haritha
- [x] ./gperfport/buildenv - Haritha
- [x] ./gnulibport/buildenv
- [x] ./xxhashport/buildenv - https://github.com/ZOSOpenTools/xxhashport/pull/7
- [x] ./libiconvport/buildenv
- [x] ./lz4port/buildenv - https://github.com/ZOSOpenTools/lz4port/pull/8
- [x] ./zotsampleport/buildenv
- [x] ./m4port/buildenv - Haritha
- [x] ./ncursesport/buildenv - Igor - https://github.com/ZOSOpenTools/ncursesport/pull/5
- [x] ./automakeport/buildenv - No C files
- [x] ./autoconfport/buildenv - No C files
- [x] ./metaport/buildenv N/A
- [x] ./libtoolport/buildenv - (https://github.com/ZOSOpenTools/libtoolport/pull/16)

We should attempt to add zoslib and if there are no regressions/issue consider adding zoslib as a implicit dependency.

**Comment by MikeFultonDev** [comment]
I think zigiport targets TSO and EBCDIC and so it might not make sense for it to use zoslib

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM are the tickmarks above correct, i.e. there is still more to do here?

**Comment by IgorTodorovskiIBM** [comment]
Yes, a bit more left to do. CMake for example needs to be converted into an ASCII application. We also wanted to add zoslib as an implicit dependency. We could have an option to disable its automatic inclusion as a dependency (for CMake..for now). If you're ok with that, we can go ahead and make that change after confirming the above unchecked tools don't regress.

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM with the rework of CMake, is this 'done' ?

**Comment by IgorTodorovskiIBM** [comment]
Yep, we just need to add it to the implicit dep list

**Comment by IgorTodorovskiIBM** [comment]
This is now complete - https://github.com/ZOSOpenTools/meta/pull/524, closing
