### ISSUE TITLE
`zopen upgrade` prints Installing ... for every non-installed package

### ISSUE THREAD

**Issue by covener** [ZOSOpenTools/meta#249]
This scared me when I tried to upgrade existing tools and saw Installing... for tons of things that are not installed:

with no args:
```
Installing autoconf...
Installing automake...
...
```

with -v, it tells you it's kidding:

```
Installing autoconf...
VERBOSE: '/u/WASTST1/zopen/prod/autoconf will not be upgraded as it is not installed.'
````

I think the Installing message should be deferred (until it's actually being upgraded)  or suppressed (verbose only)
Or minimally, "checking..."?

**Comment by MikeFultonDev** [comment]
Agreed. @IgorTodorovskiIBM fyi

**Comment by dougburns** [comment]
I had the same panic, thinking it was installing every package.
Definitely needs fixing.
If we change the message to checking, then it would be good to make the result a normal message rather than verbose only.
I.e. you get "checking" followed by a message saying what the decision was.

**Comment by IgorTodorovskiIBM** [comment]
@covener , can you confirm if this is resolved with the new zopen?

**Comment by covener** [comment]
yes, fixed with zopen-dt
