### ISSUE TITLE
zopen version ?

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/meta#258]
Shouldn't zopen have a --version option?

**Comment by Eva-Berrio** [comment]
Hi I would like to work on this

**Comment by MikeFultonDev** [comment]
Terrific ! Please put a patch together with a pull request

**Comment by Eva-Berrio** [comment]
sure :) thank you, Mike

**Comment by MikeFultonDev** [comment]
@Eva-Berrio this would still be great! @IgorTodorovskiIBM @HarithaIBM  @DevonianTeuchter what do you think? 
I tripped over this as part of working on a 'man' page for zopen and it's one of the things that man pages often have...

**Comment by DevonianTeuchter** [comment]
+1  
Should it return the version of meta or a new version for itself...?  
Zopen-install actually has a version var and  --version parameter so that needs reworking as it's not up-to-date

**Comment by MikeFultonDev** [comment]
Good question. I can’t think of a good reason for meta and zopen to have two different versions. It might be less confusing if they were the same? When metaport runs does it create a new pax file that we download? Should it?

**Comment by MikeFultonDev** [comment]
@covener here is the `zopen --version` issue

**Comment by MikeFultonDev** [comment]
ok - i did this. all complete now
