### ISSUE TITLE
Should we override fopen to handle binary I/O - "rb" or "wb"

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/meta#263]
_Originally posted by @MikeFultonDev in https://github.com/ZOSOpenTools/libiconvport/pull/13#pullrequestreview-1378199833_ 
> Thanks! Could we also get the same effect if we read and wrote in binary?

We should investigate if we can do this in zoslib and perhaps consider disabling auto-conversion if a request to read or write binary is made in fopen (rb or wb)

**Comment by MikeFultonDev** [comment]
this was provided I believe. @IgorTodorovskiIBM re-open if we still have work here.
