### ISSUE TITLE
We need a switch to add zoslib as dependency to a port during porting

### ISSUE THREAD

**Issue by HarithaIBM** [ZOSOpenTools/meta#268]
We a need switch to implicitly add zoslib as the dependency to a port or not, for instance, cmake is EBCDIC built progam, zoslib is not ready to handle this. Hence, we don't need to add zoslib as dependency here, similarly meta does not have source code to build so we not need to add zoslib to this port

**Comment by MikeFultonDev** [comment]
I believe this is done now. The parts that aren't are in another issue for zoslib cleanup
