### ISSUE TITLE
zopen install of new does not update .bootenv

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/meta#287]
When installing a new tool, e.g. man-db, the ../boot/.bootenv is not updated to include that subdir and .env - not cool :)

**Comment by v1gnesh** [comment]
Hi, think bootenv will remain just the barebones required to get going.
You can put [zopen-importenvs](https://github.com/ZOSOpenTools/meta/blob/main/bin/zopen-importenvs) in your `.bash_profile` to do it all as you log in:
```shell
cd $HOME/zopen/boot/meta/bin
. ./zopen-importenvs
cd $HOME
```
It'll take 30-40 seconds though.
Once GNU parallel and whatever else needed is ported, I'm guessing the loop can be parallellized.

**Comment by lbdyck** [comment]
Wouldn't using `find -name ".env"` be quicker?

**Comment by v1gnesh** [comment]
Maybe, but remember we'd need to `cd` into each project's directory before source-ing the file.

**Comment by IgorTodorovskiIBM** [comment]
Does the new zopen-config resolve this?
