### ISSUE TITLE
zopen-setup could report if bootstrap was already found

### ISSUE THREAD

**Issue by thomasw64** [ZOSOpenTools/meta#295]
If zopen-setup will always reinstall all packages. It would be helpful if there is a way to avoid reinstallation if it is already done.

This would be very helpful if zopen-setup is invoked via an Ansible-playbook.

Here is as-is
``` bash
bash-5.2# ls -l /var/zopen
total 16
drwxr-xr-x  25 BPXROOT  SYS1        8192 May 11 05:54 boot
drwxr-xr-x   2 BPXROOT  SYS1           0 May 11 05:40 dev
drwxr-xr-x   2 BPXROOT  SYS1           0 May 11 05:40 prod
bash-5.2# ./zopen-setup /var/zopen
Creating directories under /var/zopen
Download meta into /var/zopen/boot
Download curl into /var/zopen/boot
Download make into /var/zopen/boot
Download git into /var/zopen/boot
[recvexit] 52592640 bytes received
Download less into /var/zopen/boot
Download perl into /var/zopen/boot
Download jq into /var/zopen/boot
Download bash into /var/zopen/boot
Download diffutils into /var/zopen/boot
Download findutils into /var/zopen/boot
Download coreutils into /var/zopen/boot
Download tar into /var/zopen/boot
Download gzip into /var/zopen/boot
Download xz into /var/zopen/boot
Download bzip2 into /var/zopen/boot
Download vim into /var/zopen/boot
Download ncurses into /var/zopen/boot
Download sed into /var/zopen/boot
Download grep into /var/zopen/boot
Download gawk into /var/zopen/boot
Download man-db into /var/zopen/boot
Download groff into /var/zopen/boot
Download libiconv into /var/zopen/boot
Create .bootenv for source'ing in /var/zopen/boot
No symbolic link from /u/ibmuser/zopen to /var/zopen required
bash-5.2# 
```

It would be cool if we had an option or flag (let's say -x) that only updates if not found:
``` bash
# ./zopen-setup -x /var/zopen
Directories under /var/zopen found
Found meta at /var/zopen/boot
Found curl at /var/zopen/boot
Found make at /var/zopen/boot
Found git at /var/zopen/boot
Found less at /var/zopen/boot
Found perl at /var/zopen/boot
Found jq at /var/zopen/boot
Found bash at /var/zopen/boot
Found diffutils at /var/zopen/boot
Found findutils at /var/zopen/boot
Found coreutils at /var/zopen/boot
Found tar at /var/zopen/boot
Found gzip at /var/zopen/boot
Found xz at /var/zopen/boot
Found bzip2 at /var/zopen/boot
Found vim at /var/zopen/boot
Found ncurses at /var/zopen/boot
Found sed at /var/zopen/boot
Found grep at /var/zopen/boot
Found gawk at /var/zopen/boot
Found man-db at /var/zopen/boot
Found groff at /var/zopen/boot
Found libiconv at /var/zopen/boot
Found .bootenv for source'ing in /var/zopen/boot
No symbolic link from /u/ibmuser/zopen to /var/zopen required
# echo $?
1
```

**Comment by v1gnesh** [comment]
Hi,

I think you may be looking for `zopen-install --install-or-upgrade` ?
https://github.com/ZOSOpenTools/meta/blob/main/bin/lib/zopen-install
So if you wanted to do this through `zopen`, I believe it'll be `zopen install --install-or-upgrade`.

Pretty sure this answer is only 90% of the way though 😄

**Comment by thomasw64** [comment]
Hi @v1gnesh thanks for this answer, I think my issue is earlier, in bootstrap.

I install z/OS Open Tools on a[ Wazi as a Service](https://www.ibm.com/docs/en/wazi-aas/1.0.0) instance using ansible, and I like my playbooks to be restartable (if something fails along the line, it should pick up where it left.)

Thinking 🤔 about it I could test for the existence of the `boot`, `dev`, and `prod` directories, and I only run `zopen-setup` if they are not there. The only thing it would not capture is if the bootstrap was only done half way.

**Comment by MikeFultonDev** [comment]
@thomasw64 with the enhancements we have made to 'zopen', do you still have concerns here?

**Comment by MikeFultonDev** [comment]
I think this is good now. @thomasw64 please re-open if our new tooling doesn't address your concerns.
