### ISSUE TITLE
zopen port of the_silver_searcher

### ISSUE THREAD

**Issue by AnthonyGiorgio** [ZOSOpenTools/meta#297]
It would be nice if[ the_silver_searcher](https://github.com/ggreer/the_silver_searcher) could be ported to z/OS.  It's a **really** fast search tool for files in the zFS, and I've used it on Linux before to dig through piles of source code for text.  It's like a supercharged `grep`.

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM i think you have a discussion in meta on things people want ported - would it make sense to move this request there to get more eyes on it?

**Comment by IgorTodorovskiIBM** [comment]
@AnthonyGiorgio , if you could also post this under https://github.com/orgs/ZOSOpenTools/discussions/23 . 

@MikeFultonDev It would be nice if we can consolidate them and allow users to vote on the packages they want to see ported next.

**Comment by AnthonyGiorgio** [comment]
@IgorTodorovskiIBM [Done.](https://github.com/orgs/ZOSOpenTools/discussions/23#discussioncomment-5883430)
