### ISSUE TITLE
Newline in patches/LICENSE

### ISSUE THREAD

**Issue by v1gnesh** [ZOSOpenTools/meta#308]
ShellCheck tells me to use `echo -e` or `printf`.
https://github.com/koalaman/shellcheck/wiki/SC2028
A nitpick really, as I've manually updated the patches/LICENSE file after uploading to fix the newline.

https://github.com/ZOSOpenTools/meta/blob/2af96633af7e034dc5d42a47aebaee45ae134d6a/bin/lib/zopen-generate#L87

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM is this fixed with the move to use shellcheck?

**Comment by v1gnesh** [comment]
It's still here -  
https://github.com/ZOSOpenTools/meta/blob/b42f9ce2c8cc13eef4cee75b8547d090e92dc672/bin/zopen-generate#L113

**Comment by MikeFultonDev** [comment]
Sorry i was a little 'aggressive'. Did you want to fix it or should we leave it unassigned?

**Comment by v1gnesh** [comment]
Aggressive? Good thing I didn't notice it :stuck_out_tongue:

**Comment by IgorTodorovskiIBM** [comment]
From what I've seen, shellcheck is only capable of fixing certain kinds of issues. The rest need to be manually fixed up. It also categorizes issues with varying severities, I think info/warnings still returns 0 but I'd need to double check.

If we include coreutils or bash as a dependency, then we can probably use echo -e, but the /bin/echo -e doesn't process -e so /bin/sh users who prefer /bin/echo would be affected.

**Comment by MikeFultonDev** [comment]
I think Printf is generally viewed better than echo because echo has different behaviour across shells
