### ISSUE TITLE
offload_compiler_logic branch and some build/install troubles

### ISSUE THREAD

**Issue by v1gnesh** [ZOSOpenTools/meta#311]
I've git cloned the [offload_compiler_logic](https://github.com/zosopentools/meta/tree/offload_compiler_logic) branch into `/v1g/zopen/dev`, and then source the `.env` file within it from my `.bashrc`, effectively putting this above `boot/meta`.

This has helped silence errors such as below, when adding `comp_[go|clang]`.
```shell
VERBOSE: 'Setting up /v1g/zopen/prod/comp_go dependency environment'
go is not found
Go not found
```

**Problem 1:** Using this branch, if I don't set `ZOPEN_COMP`, it adds `xlclang` as a dependency, and that adds all the OPTS to 'Check' (test) and 'Install'.

**Problem 2:** When trying to port [esbuild](https://github.com/evanw/esbuild) with the below buildenv, it keeps tripping on the second condition check here, and keeps adding `ZOPEN_INSTALL_OPTS` (which adds `-j1 install`) and other flags (`CC=` etc.) https://github.com/ZOSOpenTools/meta/blob/c32c8ff124489289ad38d1f375ccf87e0fb95248/bin/lib/zopen-build#L1444

I can manually do `go install` and put the binary into `/v1g/zopen/prod/esbuild/bin`.
But because the install script does the additional symlink work, etc., I'd prefer `zopen build` to work.

**Problem 3:** `zopen build` is creating symlinks to the absolute path in `zopen/prod`, whereas doing `zopen install` as a user correctly creates symlinks to the relative paths.
Ex: 
`$ cd /v1g/zopen/prod`
`direnv -> /v1g/zopen/prod/direnv-master` instead of  `direnv -> direnv-master`

What's really confusing is I based the buildenv off of direnv's and powerline-go's... both of which worked fine just a few days ago. I can't _not_ use this branch because the meta from boot will insert xlclang opts into everything.

```shell
export ZOPEN_GIT_URL="https://github.com/evanw/esbuild.git"
export ZOPEN_GIT_DEPS="comp_go"
export ZOPEN_TYPE="GIT"

# Below parm is needed only if using meta branch 'offload_compiler_logic'.
# Otherwise, an empty ZOPEN_COMP inserts a dependency on xlclang.
export ZOPEN_COMP=GO

export ZOPEN_CONFIGURE="skip"
export ZOPEN_MAKE="go"
export ZOPEN_MAKE_OPTS="build ./cmd/esbuild"
export ZOPEN_MAKE_MINIMAL="yes"
export ZOPEN_CHECK="go"
export ZOPEN_CHECK_OPTS="test ./..."
export ZOPEN_CHECK_MINIMAL="yes"
export ZOPEN_INSTALL="zopen_install"

zopen_init()
{
  export GOBIN=$ZOPEN_INSTALL_DIR/bin
  mkdir -p \$ZOPEN_INSTALL_DIR/bin
}

zopen_check_results()
{
  dir="$1"
  pfx="$2"
  chk="$1/$2_check.log"

  # Echo the following information to gauge build health
  echo "actualFailures:0"
  echo "totalTests:1"
  echo "expectedFailures:0"
  echo "expectedTotalTests:1"
}

zopen_install()
{
  go install
}

zopen_append_to_env()
{
  # echo envars outside of PATH, MANPATH, LIBPATH
}

zopen_append_to_setup()
{
  # echo commands that will run when installing via setup.sh
}

zopen_get_version()
{
  $ZOPEN_INSTALL_DIR/bin/esbuild --version
}
```

**Output:**
```shell
Running Install
VERBOSE: '"zopen_install" -j1 install CC= "CPPFLAGS= " "CFLAGS= " CXX= "CXXFLAGS= " "LDFLAGS= " > /tmp/V1G.pipe 2>&1'
no Go files in /v1g/zopen/dev/esbuildport/esbuild
***ERROR: Install failed. Log: /v1g/zopen/dev/esbuildport/log/20230528_044756_install.log
zopen-build completed in 80 seconds.
```

PS: Please create a repo for esbuildport.
It builds as is, but having it under the zopen umbrella means that the fact that it builds & works will be more widely known.

**Comment by IgorTodorovskiIBM** [comment]
Looks like I missed this one. The repo esbuildport is now present.

I'll leave the issue open so that we can address the other problems you mentioned here. Thanks!

**Comment by v1gnesh** [comment]
Thank you :+1: 
No worries, I'll open a new one if I see these again.
