### ISSUE TITLE
zopen install issues

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/meta#312]
Generated my oauth key and defined in my .profile

then ran `zopen install` and got this

![image](https://github.com/ZOSOpenTools/meta/assets/42328411/e5d458cd-4f32-4946-9e39-72cef2d960eb)

and this

![image](https://github.com/ZOSOpenTools/meta/assets/42328411/e18c645e-106c-4047-9dbd-fb4a632a6735)

**Comment by lbdyck** [comment]
note under OMVS 3270

**Comment by IgorTodorovskiIBM** [comment]
Is this resolved now with the new zopen?

**Comment by MikeFultonDev** [comment]
@lbdyck re-open if still an issue.
