### ISSUE TITLE
PATH_MAX

### ISSUE THREAD

**Issue by v1gnesh** [ZOSOpenTools/meta#329]
Working on DuckDB, I've come across a few places where `PATH_MAX` is being used.
I found this [discussion on LLVM](https://reviews.llvm.org/D92110) where they use `_XOPEN_PATH_MAX` instead.

https://github.com/ZOSOpenTools/meta/blob/745f2eeadda6ddc42bba5b3e9cc5338ef7ed0689/tools/src/zopenio.h#L1-L2

If `PATH_MAX` is a common occurrence, does it make sense to handle it transparently in zoslib (introducing a dependency on zoslib)?

Or is it ok to upstream a conditional block like this?

```cpp
#ifdef __MVS__
// enjoy - https://reviews.llvm.org/D92110
#define PATH_MAX _XOPEN_PATH_MAX
#endif
```

**Comment by IgorTodorovskiIBM** [comment]
In my opinion, I would create a limits.h header override in zoslib that does the following:
```
#include_next <limits.h>
#ifndef PATH_MAX
#define PATH_MAX _XOPEN_PATH_MAX
#endif
```

**Comment by MikeFultonDev** [comment]
I like the idea of putting it in zoslib. Do we need a check with a #error if the zopen macro isn’t defined?

**Comment by IgorTodorovskiIBM** [comment]
Can we close this now that it's in zoslib?

**Comment by v1gnesh** [comment]
Yes Sir, closing it.
