### ISSUE TITLE
zopen importenv - enhancements

### ISSUE THREAD

**Issue by HarithaIBM** [ZOSOpenTools/meta#333]
Currently You can run zopen-importenv by either passing 1 or 0 arguments. If an arg is passed then build env from that location is fetched and all the dependencies are sourced, if no arg is passed then  .env under $HOME/zopen/prod or boot dir is sourced recursively.

The enhancement is in case when 1 arg is passed. If the arg passed is path to buildenv then use that buildenv from arg to set dependencies as per buildenv if the arg is the path to a directory all the .env in that path is sourced recursively.

**Comment by HarithaIBM** [comment]
more details on changes, in addition to above changes:

importenvs --> check if its executable then you source .env
restore old working dir -- i.e. code/meta/bin
append "/" for directory search for .env ie. /home/haritha/zope/prod/git if its a soft link

**Comment by IgorTodorovskiIBM** [comment]
@MikeFultonDev @HarithaIBM @DevonianTeuchter Is zopen importenv still necessary now that zopen-config pretty much handles this more or less?
