### ISSUE TITLE
doc: developper documentation improvement

### ISSUE THREAD

**Issue by kishkulk** [ZOSOpenTools/meta#335]
While going through [developing z/OS Open Tools](https://zosopentools.github.io/meta/#/Guides/developing?id=if-you-are-contributing-to-or-developing-zos-open-tools) the `zopen build` steps failed because I missed performing `zopen generate`. It would be convenient if you document `zopen generate` first and then `zopen build`.

**Comment by MikeFultonDev** [comment]
can we close this? @IgorTodorovskiIBM @kishkulk ?

**Comment by MikeFultonDev** [comment]
fixed.
