### ISSUE TITLE
After installing bash (or git?) I am unable to properly configure the tools in 'sh'

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/meta#382]
When I run from my 'sh' environment:

```
FULTONM : /home/fultonm : > . /fultonm/zopen/etc/.zopen-config
- Processed z/OS Open Tools configuration: 100% (8/8)
FULTONM : /home/fultonm : > clear
terminals database is inaccessible
FULTONM : /home/fultonm : >
```

This also takes under a second to run - so something is failing out...

If I first start 'bash', it works fine. 

FULTONM : /home/fultonm : > . /fultonm/zopen/etc/.zopen-config
![Screenshot 2023-09-04 at 2 41 25 PM](https://github.com/ZOSOpenTools/meta/assets/61100689/9c417922-1398-41c7-b1e8-19eadc497982)

**Comment by IgorTodorovskiIBM** [comment]
I tried installing bash and git and using `/bin/sh` to source the zopen-config, but I can't seem to reproduce it. I wonder if it's related to https://github.com/ZOSOpenTools/meta/issues/377, which potentially mangled your install directories

**Comment by DevonianTeuchter** [comment]
Could also not recreate.  If Igor's zopen-build fix doesn't resolve, it would be worth inserting "set -x" to line 1 in .zopen-config to see what the sourcing has set your environment to and what is detected.

**Comment by HarithaIBM** [comment]
I was unable to recreate this issue. I have installed latest zopen on a jenkins machine and tried executing the above mentioned steps in new session and it worked fine. (I did not run `bash` - there was no issue with `clear` as well)

**Comment by MikeFultonDev** [comment]
Ok. Will try this out tomorrow or whenever zoscan2b comes back online
