### ISSUE TITLE
Suggest to the user that zopen-config should be re-sourced after zopen install

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/meta#386]
Some tools like GIT, which depend on ncurses environment variables require re-sourcing of zopen-config. We should suggest to the user after installation to re-source zopen-config

**Comment by MikeFultonDev** [comment]
perhaps this problem disappears in the near future?

**Comment by MikeFultonDev** [comment]
i fixed this awhile back to put out a msg
