### ISSUE TITLE
cicd: stdout coming from buildenv is garbled in Jenkins

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/meta#39]
See https://128.168.139.253:8443/job/Port-Pipeline/234/ for an example

**Comment by mfsysprog** [comment]
Is there a way to get access to the pipelines as a non ibm employee?

**Comment by MikeFultonDev** [comment]
What particular things do you have in mind to enhance/fix?

**Comment by mfsysprog** [comment]
Well, in this case if I can perhaps understand why the output is garbled. But more in general, it might be usefull for contributers to be able to see how the automated builds are going. But I'm quite ok if the answer is that it is not possible for now.

**Comment by MikeFultonDev** [comment]
Ah yeah I have seen that. @IgorTodorovskiIBM is the expert here

**Comment by MikeFultonDev** [comment]
fixed
