### ISSUE TITLE
zopen query --list functionality

### ISSUE THREAD

**Issue by HarithaIBM** [ZOSOpenTools/meta#393]
The help command for `zopen query` is not reflecting the way `zopen query --list` is working 
the syntax shows:

`zopen-query [<option>]* [<package]*`

But,
`zopen query --list vim` lists all the available set of tools
`zopen-query vim --list` also lists all the available set of tools.

We need to define the expected o/p for this functionality and also change the help for `--list` option accordingly

**Comment by MikeFultonDev** [comment]
still broken. @DevonianTeuchter fyi

**Comment by MikeFultonDev** [comment]
I have improved the help and removed the broken verbs. Here is the new help. Will open defects for other items:
```
bin/zopen-query --help
zopen-query -  a utility for z/OS Open Tools to query packages and repos.
Usage: zopen-query [OPTION] [VERB] [PACKAGE]
  VERB is the action to take, which is one of
    --list, --remote-search, --installed
  PACKAGE is a package, specified for --remote-search
Verbs:
  --list           list all available z/OS Open Tools.
  --remote-search  regex match package against available z/OS Open Tools
  -i, --installed  list installed z/OS Open Tools.
Options:
  -v               run in verbose mode.
  -d, --details    include full details for listings.
  --no-header,     suppress the header for the output.
  --no-version,    suppress version information, return package names.
  --help           print this help
  --version        print version
```
