### ISSUE TITLE
do we need to enhance the feature of -wp or --whatprovides option?

### ISSUE THREAD

**Issue by HarithaIBM** [ZOSOpenTools/meta#396]
--whatprovides or -wp with the package name gives the o/p matching all the package* option.
Or do we have to provide info only about the executables matching this `package`?

**Comment by DevonianTeuchter** [comment]
Whatprovides should take a file and list the packages where that file was installed from - the more precise the filename, the less packages should match

Does raise a question about different packages shipping the same file - that behaviour caused conflic messages on Fedora

**Comment by MikeFultonDev** [comment]
@HarithaIBM Can you elaborate? Where is the -wp option? Is it from a particular zopen-xxx verb?

**Comment by HarithaIBM** [comment]
> @HarithaIBM Can you elaborate? Where is the -wp option? Is it from a particular zopen-xxx verb?

This was raised in regards to define the exact behaviour of the "whatprovides/wp" option.  I guess @DevonianTeuchter has answered it. We can close this, if we all agree on that.

**Comment by MikeFultonDev** [comment]
I have improved the help and removed the broken verbs. Here is the new help. Will open defects for other items:
```
bin/zopen-query --help
zopen-query -  a utility for z/OS Open Tools to query packages and repos.
Usage: zopen-query [OPTION] [VERB] [PACKAGE]
  VERB is the action to take, which is one of
    --list, --remote-search, --installed
  PACKAGE is a package, specified for --remote-search
Verbs:
  --list           list all available z/OS Open Tools.
  --remote-search  regex match package against available z/OS Open Tools
  -i, --installed  list installed z/OS Open Tools.
Options:
  -v               run in verbose mode.
  -d, --details    include full details for listings.
  --no-header,     suppress the header for the output.
  --no-version,    suppress version information, return package names.
  --help           print this help
  --version        print version
```
