### ISSUE TITLE
Pick a coding style for code in the ZOSOpenTools repositories

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/meta#4]
For patches that will go into a software package, the coding style of that package must be used, e.g. a patch in m4 would follow m4 coding guidelines.

For code that is provided in these repositories for build, we should pick a coding style.
Since many of the tools we are porting are GNU tools (at least right now), it would make sense to me that we follow that coding style: https://www.gnu.org/prep/standards/html_node/Formatting.html#Formatting
and more generally: https://www.gnu.org/prep/standards/html_node/index.html#Top

We need to decide what coding style we should use for 'sh' since that is probably the majority of our code that won't go back to a community.
@AnthonyGiorgio @IgorTodorovskiIBM @perry-ca @ccw

**Comment by perry-ca** [comment]
I think the tools should follow the style of the package too.   Even if the scripts don't make it into the package, the user will be using them in the context of the package.

And if the package doesn't have a style for scripts then fall back to gnu style.

**Comment by MikeFultonDev** [comment]
@perry-ca what about the 'utils' repo? It's not directly associated with any particular package, but is used for (hopefully) all of them. I'm thinking GNU coding conventions would make sense (see above)?

**Comment by perry-ca** [comment]
makes sense to me.  The GNU convention seems to only cover C programs.  most of the stuff in the utils repo will be shell scripts.  We could look at the Google style guide for scripting.  I haven't read it in depth so can't comment on it.  Probably the most important thing to do is to define what scripting languages & versions are allowed.  I assume everything has to be /bin/sh or more completely tools available within LE.

**Comment by MikeFultonDev** [comment]
Yes. For now our code needs to work without additional tools so that prevents us from things like python and bash. 
I will poke around for existing shell coding standards

**Comment by MikeFultonDev** [comment]
Here is the google style guide: https://google.github.io/styleguide/shellguide.html
My view is that we should follow it, with the fundamental difference being that we use the z/OS 'sh' and not bash, and therefore some guidance needs to be adjusted since the shell is different. 
Thoughts? 
There is a tool called ShellCheck: (https://www.shellcheck.net/) we can use too although I don't know if the previuos point about adjustments will mean the tool has any issues

**Comment by MikeFultonDev** [comment]
@ccw has compiled shfmt and I've put it into /usr/local/bin on zota so that we can have a consistent way to format 'sh' code.

It appears that we would want to create a .editorconfig file into the root of each repo to specify how formatting should work (I don't see a way to share the formatting for a 'system' and perhaps a 'repo' is the right scope)

Assuming we want to use shfmt (or another tool like it), we need to agree on a coding style. Here's a first thought, based on the shell guide from google:

```
[*.sh]
indent_style = space
indent_size = 2

shell_variant      = posix # like -ln=posix
switch_case_indent = true  # like -ci
function_next_line = true  # like -fn

**Comment by MikeFultonDev** [comment]
closing this off - we are using shfmt
