### ISSUE TITLE
zopen list --upgradeable shows things that are not upgradeable

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/meta#400]
![image](https://github.com/ZOSOpenTools/meta/assets/61100689/16bef223-2202-4b87-a3c9-bfb37286305f)

**Comment by IgorTodorovskiIBM** [comment]
The contents of .releaseinfo and .version appear to be the same?
```
[ITODORO@ZOSCAN2B ~/projects/zoslibport]$ cat ~/zopen-official/usr/local/zopen/make/make/.releaseinfo
4.4.1.20230705_115215
[ITODORO@ZOSCAN2B ~/projects/zoslibport]$ cat ~/zopen-official/usr/local/zopen/make/make/.version
4.4.1.20230705_115215
```

**Comment by IgorTodorovskiIBM** [comment]
I copied the logic from zopen upgrade to zopen query: https://github.com/ZOSOpenTools/meta/pull/403
