### ISSUE TITLE
zopen-query fails when there are too many tools installed

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/meta#405]
zopen upgrade which calls zopen query fails when there are too many tools installed:

```
echo: printInstalledEntries 15: /home/itodoro/zopen-official/usr/bin/lib/zopen-query 365: FSUM9209 cannot execute: reason code = c413005b: EDC5145I The paramete\ list is too long, or the message to receive was too large for the buffer.
```

The issue is that echo has a limit to the # of args:
```
[\u@\h \w]$ installedPackages=$(find . -type l)
[\u@\h \w]$ echo $installedPackages
echo: FSUM9209 cannot execute: reason code = c413005b: EDC5145I The parameter list is too long, or the message to receive was too large for the buffer.
[\u@\h \w]$
```

**Comment by MikeFultonDev** [comment]
try our echo instead of /bin/echo? or better yet printf 😁

**Comment by DevonianTeuchter** [comment]
The code grabs all symlinks within the packageinstall directory structure - which works fine unless a package ships with symlinks already [such as the ncurses man pages which ships many!!].  Fix is to ensure that the search doesn't return symlinks below the package/package tree [since there is no -depth param on standard zosfind].

**Comment by IgorTodorovskiIBM** [comment]
> try our echo instead of /bin/echo? or better yet printf 😁

printf works!



> The code grabs all symlinks within the packageinstall directory structure - which works fine unless a package ships with symlinks already [such as the ncurses man pages which ships many!!]. Fix is to ensure that the search doesn't return symlinks below the package/package tree [since there is no -depth param on standard zosfind].

I would suggest bundling findutils but there's an issue where it doesn't close file descriptors: https://github.com/ZOSOpenTools/findutilsport/issues/16 which I'd prefer if we fix first.

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM sounds like this is now fixed correct?
