### ISSUE TITLE
Eliminate aliases in the 'zopen' set of verbs or provide proper help

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/meta#418]
Right now zopen install, zopen upgrade do the same thing and are aliases, but if you ask for help, it'll print out the wrong one.
We should either get rid of aliases or pass in the real verb name to the underlying code so it can have proper diagnostics.

My vote is to eliminate aliases (stick with install and list and eliminate aliases?)

@IgorTodorovskiIBM @DevonianTeuchter @covener your comments appreciated.

**Comment by covener** [comment]
> My vote is to eliminate aliases (stick with install and list and eliminate aliases?)
+1

**Comment by IgorTodorovskiIBM** [comment]
Most package managers have an `upgrade` command. I'd prefer to at least keep that one intact since it's more intuitative then zopen install --upgrade. We should at a minimum update the help to reflect the command used.

**Comment by DevonianTeuchter** [comment]
Passing through the command used would make sense - as Igor indicates, most package managers have an "upgrade" verb. That being said, some of the aliased verbs like query, list and search could be dropped/merged but whatif the functionality for each was split into new modules [with any common functionality added into common.inc for reuse] - in effect having more smaller specialized modules.

**Comment by MikeFultonDev** [comment]
I have removed a number of broken verbs from zopen-query so this isn't too far off now.

I have improved the help and removed the broken verbs. Here is the new help. Will open defects for other items:
```
bin/zopen-query --help
zopen-query -  a utility for z/OS Open Tools to query packages and repos.
Usage: zopen-query [OPTION] [VERB] [PACKAGE]
  VERB is the action to take, which is one of
    --list, --remote-search, --installed
  PACKAGE is a package, specified for --remote-search
Verbs:
  --list           list all available z/OS Open Tools.
  --remote-search  regex match package against available z/OS Open Tools
  -i, --installed  list installed z/OS Open Tools.
Options:
  -v               run in verbose mode.
  -d, --details    include full details for listings.
  --no-header,     suppress the header for the output.
  --no-version,    suppress version information, return package names.
  --help           print this help
  --version        print version
```
