### ISSUE TITLE
zopen alt -d option doesn't do anything

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/meta#419]
At least, nothing I see... 

```
FULTONM@ZOSCAN2B bash ~> zopen alt -d 2 git
1: git-2.41.0.20230906_213139.zos  <-  current
2: git-2.41.0.20230912_202104.zos
FULTONM@ZOSCAN2B bash ~> zopen alt -d 1 git
1: git-2.41.0.20230906_213139.zos  <-  current
2: git-2.41.0.20230912_202104.zos
```

Although perhaps 'default' is different than 'current' ?

**Comment by IgorTodorovskiIBM** [comment]
Adding the option -s sets the alternative package for me. Perhaps a better name is "option" rather than "default option" to avoid the prompt.

**Comment by IgorTodorovskiIBM** [comment]
Comparing to linux's alternatives command:
```
       alternatives --list
       alternatives --set <name> <path>
       alternatives --display <name>
```
I agree with Mike that it's probably more intuitive to specify the path vs a number.

**Comment by DevonianTeuchter** [comment]
-d was required to stop the user-interaction during zopen-init when the initial fork needed to install and pin itself; it was a bit of a "workaround" but no longer needed. The --set parameter should behave like the "alternatives" and the default behaviour for zopen-alt is the similar to alternatives --display <name>  showing the current version [but also lists all alternatives]
