### ISSUE TITLE
Should we have shell scripts called zopen-xxx that can be run directly?

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/meta#436]
Right now, we have:
```
bin
  +- lib
```

as our structure, with `zopen` in bin and the `zopen-xxx` shell scripts (that presumably aren't meant to be called directly) in `bin/lib`. 
Is there any reason to restrict the underlying scripts to not be run directly? 

There are two reasons this would seem nice:
- it makes it clearer for the invoker how options and such are processed and you don't end up with the slightly clunky `zopen <verb> <options> <parameters>`
- it would give us a direct mapping from 'man' pages and docs to the actual scripts

@IgorTodorovskiIBM @DevonianTeuchter @HarithaIBM and anyone else... arrows expected...

**Comment by IgorTodorovskiIBM** [comment]
I believe git allows the dash form scripts to be run explicitly as well, so I'm ok with this.

I initially decided to separate the scripts into option commands because I wanted the user's entry point to be `zopen`. When the user types `zopen`, they get the help which describes what the meaning of each command is. I think this is common convention is cli tools these days, including git, brew, etc. One negative is the lack of auto-complete, but new shells like zsh overcome this:

```
$ git <tab>
add       -- add file contents to the index
bisect    -- find by binary search the change that introduced a bug
branch    -- list, create, or delete branches
checkout  -- checkout a branch or paths to the working tree
clone     -- clone a repository into a new directory
commit    -- record changes to the repository
diff      -- show changes between commits, commit and working tree,
fetch     -- download objects and refs from another repository
grep      -- print lines matching a pattern
init      -- create an empty Git repository or reinitialize an exis
log       -- show commit logs
merge     -- join two or more development histories together
mv        -- move or rename a file, a directory, or a symlink
pull      -- fetch from and merge with another repository or a loca
push      -- update remote refs along with associated objects
rebase    -- forward-port local commits to the updated upstream hea
reset     -- reset current HEAD to the specified state
restore   -- restore working tree files
rm        -- remove files from the working tree and from the index
show      -- show various types of objects
status    -- show the working tree status
switch    -- switch branches
tag       -- create, list, delete or verify a tag object signed wit
```
The alternative for bash is https://github.com/scop/bash-completion

**Comment by MikeFultonDev** [comment]
Actually, I thought that too but git _does not_ let you run the commands directly (and least not on Mac or z/OS when I tried, e.g. `git add` works but `git-add` does not.

**Comment by DevonianTeuchter** [comment]
running /usr/libexec/git-core/git-fetch does work on fedora; git-fetch is a symlink back to git itself so it must check how it was instantiated.
I like @IgorTodorovskiIBM 's approach in that `zopen --help`  lists all the available commands/verbs and an explanation for each - while a `zopen <verb> --help` would list the specific help for that verb - very similar to docker/podman's approach.

**Comment by v1gnesh** [comment]
Some tools make it more fun by doing it like `git help push`.

**Comment by MikeFultonDev** [comment]
done
