### ISSUE TITLE
zopen clone spits out errors

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/meta#448]
I created a 'zopen' installation under /home/fultonm/zopen.

I then did a clone to /home/fultonm/cloned and got the following:

![image](https://github.com/ZOSOpenTools/meta/assets/61100689/09383f73-1160-4596-9204-1640384f56d3)

@DevonianTeuchter please tell me if you won't have time to look at this and I can take a look... I want to be able to write a blog showing how someone can install tools, test them out, them 'clone' them to the correct target location.

@IgorTodorovskiIBM fyi

**Comment by DevonianTeuchter** [comment]
Looks like it ignored your new FS location and tried to overwrite your existing location... let me investigate

**Comment by MikeFultonDev** [comment]
thanks! I tried to hack a fix but failed 😩
