### ISSUE TITLE
Update to IBM Open XL C/C++

### ISSUE THREAD

**Issue by Crosswind** [ZOSOpenTools/meta#46]
Hi all,

the documentation currently suggests to use IBM XL C/C++ v2.4.1 compiler. Now, I got curious because it specifically mentions z/OS 2.4 but we are running 2.5. [Back in May](https://www-40.ibm.com/servers/resourcelink/svc00100.nsf/pages/openXlCC++11ForZOs24AndZOs25?OpenDocument)  the IBM Open XL C/C++ v1.1 compiler was released.

What is the strategy in moving over to Open xlclang? Which - if I read the docs correctly - targets our use case exactly: enhance porting distributed software over to z/OS. 
It doesn’t seem to run on z/OS 2.3 but you can still compile for backwards compatibility if needed. Most customers should be moving to 2.4 anyways so that shouldn’t be an issue.

I haven’t myself tried building the existing projects with that compiler. Are there any obvious obstacles that would hinder using the new compiler? I’m happy to experiment a bit and report back my results. 

Cheers - David

**Comment by v1gnesh** [comment]
Unrelated comment but hopefully it's helpful as feedback/a request.
Naming this Open XL C/C++ is annoying.
It's open but it's not really, because you get it for free only if you also pay for XL C/C++.

**Comment by MikeFultonDev** [comment]
IBM is working with the LLVM and Clang community: https://www.ibm.com/docs/en/open-xl-c-cpp-zos/1.1?topic=new-llvm-clang-infrastructure 
The strategy is definitely to migrate to a truly open C/C++ compiler that people could get either unsupported for free, or supported at a cost, like Open Source software from other vendors, e.g. RedHat. 

I can't provide a specific date when or if this would happen unfortunately. If/when we can provide a better answer, we'll definitely put it here!

**Comment by MikeFultonDev** [comment]
@v1gnesh @Crosswind I've added a PR to clarify that the compiler is indeed priced (since it has a pre-req of the base C/C++ optionally priced feature on z/OS): https://github.com/ZOSOpenTools/meta/pull/53
