### ISSUE TITLE
zopen build pulls in too many dependencies

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/meta#462]
zopen build does a 'transitive closure' of build dependencies, which is more than necessary.

What is required is the build dependencies that are listed for itself, and then for each of those packages, it needs the _runtime_ dependencies of the tools.

So for example if autoconf has a build dependency on:
```
curl gzip make m4 perl zlib texinfo automake
```

then it needs those programs as well as whatever those tools need to _run_. 

I don't _think_ this will cause a bug, although it will pull in more than it should.

@IgorTodorovskiIBM @DevonianTeuchter @HarithaIBM fyi

**Comment by IgorTodorovskiIBM** [comment]
As we talked earlier, `zopen build` sources the env for each build dependency and build dependency's env has logic to source the env of its runtime dependencies. With that said, we can probably optimize it such that we're not double sourcing envs.

**Comment by MikeFultonDev** [comment]
Thanks! My misunderstanding. Closing
