### ISSUE TITLE
zopen upgrade fails

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/meta#522]
getting this:

![image](https://github.com/ZOSOpenTools/meta/assets/42328411/049398ef-11b2-4b17-a527-9826b58a3e15)

**Comment by lbdyck** [comment]
tried to upgrade meta and got this

![image](https://github.com/ZOSOpenTools/meta/assets/42328411/288c779a-a96b-4a34-86cf-d301dd8fe6c0)

**Comment by MikeFultonDev** [comment]
@lbdyck if you issue: `zopen --version` what do you get?

@DevonianTeuchter fyi

**Comment by lbdyck** [comment]
zopen (zopen tools) 0.7.0

**Comment by lbdyck** [comment]
just tried `zopen upgrade git` and got this

/u/lbdyck>zopen upgrade git                                                                                                         
- Querying remote repo for latest package information                                                                               
Installing package: git                                                                                                             
handlePackageInstall 169: installPorts 6: /u/lbdyck/zopen/usr/local/bin/zopen-install 657: FSUM7726 cannot fork: reason code = 0b250
012: EDC5112I Resource temporarily unavailable.

**Comment by MikeFultonDev** [comment]
i haven't seen that one personally @lbdyck . As part of problem determination, can you see if it fails if you come in via 'ssh'? I'm wondering if it's part of the OMVS special processing? 
Also, if you can show the output from:
```
ulimit -a
```

**Comment by lbdyck** [comment]
Using ssh:

```
/u/lbdyck>ulimit -a
core file         8192b
cpu time          1000
data size         unlimited
file size         unlimited
stack size        unlimited
file descriptors  64000
address space     204800k
memory above bar  2048m
```

and

```
/u/lbdyck>zopen upgrade git
- Querying remote repo for latest package information
installPorts 4294966828: /u/lbdyck/zopen/usr/local/bin/zopen-install 657: FSUM7726 cannot fork: reason code = 0b250012: EDC5112I Resource temporarily unavailable.
/u/lbdyck>
```

**Comment by DevonianTeuchter** [comment]
Just recreated this with our test harness when investigating something else! Out of processes it seems.  Do you either have a large number of processes running (zopen-* ones being of concern) or low maxprocs values for your user/system?

**Comment by DevonianTeuchter** [comment]
Root cause appears to be zopen scripts not terminating; these build up and eventually hit MAXPROCSYS for the user/system so no further processes can be created
