### ISSUE TITLE
zopen remove perl takes a very long time

### ISSUE THREAD

**Issue by manfredlotz** [ZOSOpenTools/meta#531]
When de-installing `perl` with `zopen remove perl` I takes awfully long.

![image](https://github.com/ZOSOpenTools/meta/assets/192842/da07b204-21df-41b2-87ae-1332028034b7)

```
real    1m32.141s
user    0m42.349s
sys     0m14.116s
```

I should mention that removing other utilities was fast. Perhaps something which happens only with `perl`

**Comment by DevonianTeuchter** [comment]
The time taken is directly related to the number of files that a particular tool installs due to a file-system traversal.  Small utilities like xz or wget will uninstall quickly; those that supply lots of files [perl, ncurses,..].

**Comment by manfredlotz** [comment]
Ok, so Perl (incl. its dependencies) is a good example for something which should be improved.

Nevertheless, admittedly a `zopen remove...` doesn't happen such often.

**Comment by MikeFultonDev** [comment]
I would like to roll this in under 533 if that's ok with you @manfredlotz - i'll add a link to this. yell if you want and just re-open if that's better for you. closing as 'duplicate' (sort of) of 533.

**Comment by manfredlotz** [comment]
@MikeFultonDev, I fully agree as on the one hand it should be fixed but on the other hand it is not the most urgent issue to fix.
