### ISSUE TITLE
zopen upgrade -y fails with error

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/meta#554]
If I do:
```
FULTONM@ZOSCAN2B ~/zopen/dev/phpport>zopen upgrade -y
- Querying for installed packages
|
- Querying remote repo for latest package information
***ERROR: The following requested port(s) do not exist:
	man 5
```

If I specify particular entries, e.g.
```
zopen upgrade -y man-db git bash vim texinfo curl autoconf automake c3270
```

it works. 

@IgorTodorovskiIBM @DevonianTeuchter fyi

**Comment by MikeFultonDev** [comment]
This might be partially because I (for some reason) had a 'man' and a 'perl5' package on my list of installed packages even though those are not valid packages (perhaps they were from a failed 'dev' build?)
After I remove the 'man' and 'perl5' builds, then:
```
zopen upgrade -y
```
works.

**Comment by IgorTodorovskiIBM** [comment]
zopen upgrade retrieves the list of installed tools with `zopen-query list --installed --no-header --no-versions` . It seems to be reporting dev built packages as well. I have several in my case as well.

We should filter those out. `zopen-query` does a find on the filesystem for installed packages: `cd "${ZOPEN_PKGINSTALL}" && zosfind . -type l`. We should probably introduce an additional check to make sure it's available online as well. (we could invent a new option for this if needed).

**Comment by DevonianTeuchter** [comment]
zopen-query's zosfind command isn't ideal either:
`cd "${ZOPEN_PKGINSTALL}" && zosfind . -type l`
would be better as
`cd "${ZOPEN_PKGINSTALL}" && zosfind  ./*/. ! -name . -prune -type l`
and then add on any filtering on dev packages...
[did have a fix to that in my paxinstall PR]

**Comment by MikeFultonDev** [comment]
this seems to be working for me now. If it does hit a problem it says where it is.
