### ISSUE TITLE
Allow tools to display help/version regardless if zopen-config is sourced

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/meta#555]
This is preventing `zopen-help2man` from running correctly on platforms like Linux.

Workaround is to set  `export ZOPEN_ROOTFS=<value>`

**Comment by MikeFultonDev** [comment]
Interesting. Which of the scripts are intended to run off z/OS ?

**Comment by DevonianTeuchter** [comment]
> Interesting. Which of the scripts are intended to run off z/OS ?

Given they should be POSIX compliant, all of them 😂  Haven't tried them though - although I develop on Linux, never thought to actually try running them there!
Is there a need for them to be able to run off-z ?

**Comment by IgorTodorovskiIBM** [comment]
This was in regards to zopen-help2man, which was used to generate the man pages and then html docs (code borrowed from @MikeFultonDev :) ).

**Comment by MikeFultonDev** [comment]
so... since this is a slightly odd thing to do (running z/os tools on linux), is it unreasonable to set the ZOPEN_ROOTFS as a work-around? I don't think we'd want to _in general_ support running the tools off z/OS so maybe having to jump through a small hoop is ok?

**Comment by IgorTodorovskiIBM** [comment]
> so... since this is a slightly odd thing to do (running z/os tools on linux), is it unreasonable to set the ZOPEN_ROOTFS as a work-around? I don't think we'd want to _in general_ support running the tools off z/OS so maybe having to jump through a small hoop is ok?

I think that makes sense.

But should we allow z/OS users to run `zopen <command> --help` if they wanted to view the help without first having sourced the zopen-config?

**Comment by MikeFultonDev** [comment]
Do you see that as something common to do? I am imagining folks would just run the config first to set up their environment. What would the scenario be?

**Comment by IgorTodorovskiIBM** [comment]
> Do you see that as something common to do? I am imagining folks would just run the config first to set up their environment. What would the scenario be?

Could be an alternative to `man`, to understand what the tool can do prior to setting up the environment.

**Comment by MikeFultonDev** [comment]
If you think it's important, we can add it. I'm not sure how we test it to ensure it doesn't get broken... Perhaps just having it as part of the doc build process would suffice.

**Comment by IgorTodorovskiIBM** [comment]
It's a lower priority, I have set ZOPEN_ROOTFS to a random string for now to get around it. We can reopen if someone else asks.
