### ISSUE TITLE
zopen clean --unused cleaning more than it should

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/meta#569]
In the below command, I specify that I want to clean the bash package, but it is also cleaning other packages containing bash 
```
zopen clean -u bash
/home/itodoro/zopen/usr/local/zopen/bash/bash-5.2.15.20231007_025655.zos
1: bash/bash-5.2.15.20230920_202747.zos <- Removed
2: bash/bash-5.2.15 <- Removed
3: bash/bash-5.2.15.20231007_025655.zos  <-  current
4: cmake/CMake-heads.v3.24.2.20230301_161451.zos/share/bash-completion <- Removed
5: cmake/CMake-heads.v3.27.6/share/bash-completion <- Removed
6: CMake/CMake-heads.v3.27.6/share/bash-completion <- Removed
7: cli/cli-trunk/share/bash-completion <- Removed
8: githubcli/githubcli-DEV/share/bash-completion <- Removed
9: githubcli/githubcli-DEV.20231106_205638.zos/share/bash-completion <- Removed
10: githubcli/githubcli-DEV.20231107_213716.zos/share/bash-completion <- Removed
11: githubcli/githubcli-DEV.20231107_214756.zos/share/bash-completion <- Removed
- Removal of unused package versions complete
```

**Comment by MikeFultonDev** [comment]
@IgorTodorovskiIBM for the ones that were 'overly cleaned', are they dev packages?

**Comment by MikeFultonDev** [comment]
should we be adding 'findutils' to our base set of tools we package up so that we can have a reliable find (with -print0) and xargs (with -0) ?

**Comment by IgorTodorovskiIBM** [comment]
> githubcli

Some are (CMake, cli), and are not (cmake, githubcli)

> should we be adding 'findutils' to our base set of tools we package up so that we can have a reliable find (with -print0) and xargs (with -0) ?

I'm ok with expanding our embedded tools as long the package doesn't grow too big. findutils is only 2mb so it should be ok. We could even add moreutils for `parallel`
