### ISSUE TITLE
.depsenv is not sourced in .env in gpg 

### ISSUE THREAD

**Issue by HarithaIBM** [ZOSOpenTools/meta#571]
.depsenv is not sourced in .env in gpg. Hence there is an issue with PINENTRY_HOME for gpg
reference - https://github.com/ZOSOpenTools/gpgport/issues/6#issuecomment-1801914395

**Comment by IgorTodorovskiIBM** [comment]
@HarithaIBM is this still an issue? Or is it only with respect to installing pax releases manually?

**Comment by HarithaIBM** [comment]
Yes its related to installing pax files. So closing this issue
