### ISSUE TITLE
upgrade 0.8.0 to 0.8.1 fails

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/meta#608]
![image](https://github.com/ZOSOpenTools/meta/assets/42328411/bdf8c23d-d318-4cb3-9571-37288847d175)

**Comment by IgorTodorovskiIBM** [comment]
Good catch, we forgot to update the version.

**Comment by IgorTodorovskiIBM** [comment]
@lbdyck can you try this again? it should be fixed now

**Comment by lbdyck** [comment]
i followed the `rm` from another meta ticket and it worked just fine.
