### ISSUE TITLE
zopen cpu timings

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/meta#631]
Are these timings to be expected?
thanks

[zopen_timings.txt](https://github.com/ZOSOpenTools/meta/files/13641794/zopen_timings.txt)

time zopen list --upgradeable
real    0m31.907s
user    0m19.830s
sys     0m6.610s

time zopen list --installed
real    0m19.168s
user    0m6.326s
sys     0m2.109s

time zopen list --installed --no-version
real    0m0.682s
user    0m0.288s
sys     0m0.096s

time zopen list
real    0m30.938s
user    0m19.480s
sys     0m6.493s

**Comment by DevonianTeuchter** [comment]
yes - at present.  There is a filesystem traversal for each individual package when --no-version is NOT specified to pull out version data, with the time scaling directly with the number of packages.  It's on the "roadmap" to resolve

**Comment by gngrossi** [comment]
Sounds good, I will close.
thanks
