### ISSUE TITLE
zopen-promote issues

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/meta#663]
1. `man zopen-promote` is garbled (via ssh):
![image](https://github.com/ZOSOpenTools/meta/assets/42328411/fc92219b-171e-4dc9-9402-5ed72fc9afc8)

Under OMVS this is generated `groff: fatal error: cannot load 'DESC' description file for device 'utf8' `

2. `zopen-promote --help` displays the entire help - should pipe thru `less` for easier paging /reading

3. after it is complete it really isn't - it keeps going:
![image](https://github.com/ZOSOpenTools/meta/assets/42328411/4c8dda96-9032-49b5-a5d6-ac4d0d1d7d20)

But it is really checking things and building the `etc/zopen-config` - there should be a message along with the spinning /

4. Ideally would like to be able to select which packages to promote.  For example I may only want to promote `git` and `bash` along with any prereqs and definitely do not want to promote `zopen` :)

**Comment by lbdyck** [comment]
Also - `zopen` does not list `promote` as an option and it isn't in the `zopen` man page.

**Comment by peter-sylvester** [comment]
On OMVS there is "simply"a line length problem. Longer lines are split and thus scrolled away. One has the "q" or enter option, but there was too much output. Once I had a little thingy to remove the few blanks. But anyway, the man might be limited to 72 characters per line ?

**Comment by MikeFultonDev** [comment]
@lbdyck there are 2 separate problems here. One is zopen-promote not functioning the way you want and one is the man page being garbled. I have opened #665 for the usability issues.

**Comment by MikeFultonDev** [comment]
> Also - `zopen` does not list `promote` as an option and it isn't in the `zopen` man page.

This is on purpose. zopen-promote is still in 'beta testing' 😁 ... We will add it to the main 'zopen' once it's considered fully baked (@DevonianTeuchter fyi)

**Comment by MikeFultonDev** [comment]
> On OMVS there is "simply"a line length problem. Longer lines are split and thus scrolled away. One has the "q" or enter option, but there was too much output. Once I had a little thingy to remove the few blanks. Actually, the man command uses escape sequences, and they are not removed in the OMVS dumb terminal. As far as I understand, it is just /bin/man that is called?

It is a bit confusing, but there are actually 2 'man' programs on z/OS if you install the z/OS Open Tools man program. This is because the z/OS UNIX System Services 'man' under /bin/man is very limited in function and uses proprietary format man pages, so we added in a z/OS Open Tools man tool so that all the Open Source tools we are porting can have their man pages shown. For the most part, z/OS Open Tools 'man' from the man-db package can display both types of man pages (it fails over to the underlying system /bin/man for the man pages provided by z/OS). The only wrinkle is the handful of commands that are in both UNIX System Services and z/OS Open Tools (man is one, and cp is another good example). In those cases, you have to set the MANPATH and run the specific 'man' program if you want the underlying z/OS man pages

**Comment by MikeFultonDev** [comment]
> 1. `man zopen-promote` is garbled (via ssh):
>    ![image](https://private-user-images.githubusercontent.com/42328411/297523790-fc92219b-171e-4dc9-9402-5ed72fc9afc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzQ4NDEsIm5iZiI6MTcwNTYzNDU0MSwicGF0aCI6Ii80MjMyODQxMS8yOTc1MjM3OTAtZmM5MjIxOWItMTcxZS00ZGM5LTk0MDItNWVkNzJmYzlhZmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAzMjIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MjZjYzEyNzY2YTEwYTI0ZTNhZmI1NWIzMjBhMTE0ZjRmZWQ2NTdmZjRiNTAzMGJhNzQ4NmUzMTQ3YzBiZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rbpqr_7ShZTlIFPiiDSvsyCXJda61aoSvi6YuWhjxXo)
> 
> Under OMVS this is generated `groff: fatal error: cannot load 'DESC' description file for device 'utf8' `
> 
> 2. `zopen-promote --help` displays the entire help - should pipe thru `less` for easier paging /reading
> 3. after it is complete it really isn't - it keeps going:
>    ![image](https://private-user-images.githubusercontent.com/42328411/297524201-4c8dda96-9032-49b5-a5d6-ac4d0d1d7d20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MzQ4NDEsIm5iZiI6MTcwNTYzNDU0MSwicGF0aCI6Ii80MjMyODQxMS8yOTc1MjQyMDEtNGM4ZGRhOTYtOTAzMi00OWI1LWE1ZDYtYWM0ZDBkMWQ3ZDIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDAzMjIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MGZlOGMxYzAwNzU2ZDI5MTNmZWJmMTZlNmM4YWE5MWY4ZTFlNGQxNTc5NjcyNGEyMGU5M2EwNGQyN2MzZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4XAOFdvKO9sI8nqlb9S3pmEU4PSwB9vMzUcG8aIKTRY)
> 
> But it is really checking things and building the `etc/zopen-config` - there should be a message along with the spinning /
> 
> 4. Ideally would like to be able to select which packages to promote.  For example I may only want to promote `git` and `bash` along with any prereqs and definitely do not want to promote `zopen` :)

`zopen-promote --help` 'worked' for me - it completed and didn't keep running. I was able to reproduce the gibberish for man zopen-promote

**Comment by lbdyck** [comment]
`zopen-promote --help` does complete but if the ssh window isn't large enough it keeps going until it finishes requiring the user to scroll back up to view the start of the help.

https://github.com/ZOSOpenTools/meta/assets/42328411/d9c78d23-ffd5-4cf8-b6f3-0168fa2c7761

**Comment by MikeFultonDev** [comment]
That is standard for help I believe. If you want to get more control you can pipe it to more or less eg

zopen-promote —help | more

**Comment by lbdyck** [comment]
but should the `--help` work that way or is there a better way :)

**Comment by peter-sylvester** [comment]
IMHO, there are ways:  compare  'curl --help'  to 'man curl'  ,  'curl --verbose help' and  'curl --help all'
best

**Comment by MikeFultonDev** [comment]
Fair enough... We can do better. I opened a separate issue: https://github.com/ZOSOpenTools/meta/issues/667
