### ISSUE TITLE
Should we make --enable-relocatable the default for configure?

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/meta#7]
@IgorTodorovskiIBM is in the process of adding `--enable-relocatable` for Perl and I just saw this option is also available for Bison.
This seems like a good 'default' to go with, but would like other people's input before changing 'build.sh' 
@ccw-1 @perry-ca @jshimoda9323

**Comment by IgorTodorovskiIBM** [comment]
We resolved this by having the .env modify the harcoded install entries upon first sourcing
