### ISSUE TITLE
zopen query --installed pkg ignores pkg

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/meta#700]
they syntax implies this should work but it doesn't

![image](https://github.com/ZOSOpenTools/meta/assets/42328411/9d67a8f3-930f-4835-b383-9e763d232563)

**Comment by IgorTodorovskiIBM** [comment]
There's a blurb saying it is to be used with --remote-search:
```
PACKAGE is a package, specified for --remote-search
```
Let me know if that's clear or if we need to make it clearer:

```
PACKAGE is a package and is only recognized with --remote-search option
```

With all that said, I think it makes sense to support PACKAGE with --installed. Sometimes you just want to know if a given tool is installed.

**Comment by lbdyck** [comment]
that works - thanks
