### ISSUE TITLE
GettingStarted: provide a tool to create a 'boot' release of a software package

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/meta#73]
I have been working on a general tool that will setup an initial z/OS Open Tools environment on a z/OS system.
The details are in the 'GettingStarted' branch on this repo, but one piece I would like to improve on is how to set up a 'boot release' for a package.
As our code progresses, we will want to update the set of code that we use for boot (right now, it's a stable version of git, curl, gzip, tar, utils, make). The way I mark these releases is to manually set a tag called 'boot' on each of these software packages.

This issue is to create a tool with an interface like:

```
createboot <release>
```

which will create a new release _from_ the current release called `<release>`. The new release should have a fixed name (e.g. boot-release) and be tagged with 'boot' and have the assets from release `<release>` copied into it (in particular, the pax file).

**Comment by MikeFultonDev** [comment]
The easiest way to implement this is to use the 'releases' APIs from github: https://docs.github.com/en/rest/releases/releases to:
- list the specified release and ensure it exists
- download the assets from the specified release
- if there is an existing release called 'boot-release' to delete it
- if there is an existing tag called 'boot' to delete it
- create the new release 'boot-release' with tag 'boot' against the same commit level as the specified release, and upload the assets from the original release

**Comment by MikeFultonDev** [comment]
Hi @HarithaIBM . If you could work on this, that would be great. I know you have other stuff on your plate too - please work with @IgorTodorovskiIBM on the right priority of this compared to your other items... Hopefully this will be a fun one.

**Comment by HarithaIBM** [comment]
Hello Mike, Sure! I will.

**Comment by HarithaIBM** [comment]
Hi Mike! I have started scripting using jq library for the above requirement. I have assumed that the user will pass the owner and the name of the repo as arguments along with the release name, as of now!  I will be coding for the 4th requirement and 5th requirement today. 
As suggested by Igor, i have used https://api.github.com/repos/OWNERNAME/REPO/releases/tags/boot to check if there are any releases tagged as boot and am deleting the corresponding releases as well. I will add more implementation details by EOD. You can suggest if there is any gap. Thank you!

**Comment by MikeFultonDev** [comment]
done!
