### ISSUE TITLE
Add options in zopen audit to remove or upgrade packages with vulnerabilities

### ISSUE THREAD

**Issue by KeplerBoyce** [ZOSOpenTools/meta#818]
Add flags to `zopen audit` command to allow for removing all packages with vulnerabilities and upgrading all packages with vulnerabilities (if newer versions are available that resolve any vulnerabilities).

**Comment by v1gnesh** [comment]
How about a top level verb - `zopen yank`?
For upgrading, it'll be the existing `zopen upgrade/update`.
`zopen audit --try-resolve` could be a flag that shows what's up, and confirms again with Y/N on whether we want it to go ahead with an update.
