### ISSUE TITLE
Downloaded packages clutter up the zopen directory

### ISSUE THREAD

**Issue by AnthonyGiorgio** [ZOSOpenTools/meta#87]
After using zopen for a while, the downloaded packages tarballs start to clutter up the filesystem.  It would be nice if these could live in a separate `downloads` directory.  They could also be removed at some point when a tarball is no longer useful.

**Comment by MikeFultonDev** [comment]
@AnthonyGiorgio i think this is better now. Please re-open if you think there are still UX issues here.
