### ISSUE TITLE
Enhance boot tool to retain previous boot releases on creating new boot-release

### ISSUE THREAD

**Issue by HarithaIBM** [ZOSOpenTools/meta#92]
Enhance boot tool to retain previous boot releases on creating new boot-release

**Comment by HarithaIBM** [comment]
Enhanced the tool to retain the release descriptions and also the boot-release created from this tool is not marked as latest.

**Comment by MikeFultonDev** [comment]
@HarithaIBM i think this is 'complete'. Please re-open if not
